[package]
name = "rust-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.29"
wgpu = "0.20"
pollster = "0.3"
bytemuck = { version = "1.14", features = ["derive"] }
glam = { version = "0.27", features = ["bytemuck", "serde"] }
log = "0.4"
env_logger = "0.11"

# 14 форматов картинок + HDR/EXR для IBL.
image = { version = "0.25", default-features = false, features = [
    "png", "jpeg", "gif", "webp", "bmp", "tiff", "tga", "dds",
    "hdr", "exr", "ico", "pnm", "qoi", "ff"
] }

flate2 = { version = "1", default-features = false, features = ["rust_backend"] }

anyhow = "1"
gltf = { version = "1.4", default-features = false, features = ["import", "utils", "names"] }
serde = { version = "1", features = ["derive"] }
ron = "0.12"

egui = "0.28"
egui-wgpu = "0.28"
egui-winit = "0.28"

# Аудио (процедурный, без внешних ассетов).
rodio = { version = "0.22.2", default-features = false, features = ["playback"] }

# Нативный диалог выбора файлов.
rfd = "0.17.2"